// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expenses.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Expenses module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_RegistrationBuilder(
		expenses.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Expenses.ACT_Registration");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static void aCT_Registration(
		IContext context,
		expenses.proxies.Registration _registration
	)
	{
		aCT_RegistrationBuilder(
				_registration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TeamMember_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Expenses.ACT_TeamMember_Create");
		return builder;
	}

	public static void aCT_TeamMember_Create(IContext context)
	{
		aCT_TeamMember_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bCO_TeamMember_CheckUserRoleSelectionBuilder(
		expenses.proxies.TeamMember _teamMember
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Expenses.BCO_TeamMember_CheckUserRoleSelection");
		builder = builder.withParam("TeamMember", _teamMember);
		return builder;
	}

	public static boolean bCO_TeamMember_CheckUserRoleSelection(
		IContext context,
		expenses.proxies.TeamMember _teamMember
	)
	{
		Object result = bCO_TeamMember_CheckUserRoleSelectionBuilder(
				_teamMember
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder myFirstLogicBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Expenses.MyFirstLogic");
		return builder;
	}

	public static void myFirstLogic(IContext context)
	{
		myFirstLogicBuilder().execute(context);
	}
}
